apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/VK-Paints/vkpaints-helm-chart.git'
    targetRevision: main
    path: charts/frontend
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vkpaints-dev-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
